### ISSUE TITLE
Add classification for all areas

### ISSUE THREAD

**Issue by carl3** [OSVTAC/osv-data-converter#4]
There is an area.classification defined, but the only value used is "Precinct". Other classifications should be added for the areas representing districts, e.g. Neighborhood, Unified School District, Transit District, etc.

The intent is that classification is assigned from a controlled vocabulary (to be defined) with hierarchic definitions, e.g. 
```
    Education
        Community College District
        School District
            Elementary School District
```

**Comment by catrope** [comment]
Fixed by c8287a3ff0ccc1367d521de77a10e86a5965f215, be7ddb8a8bc76d1e652abeda90c24f5385caec44 and 5e7c5da3fdd2ad85c3117f305febf13b641ec4a0 among others
